class Student {
  final String id;
  final String email;
  final String login;
  final String first_name;
  final String last_name;
  final String usual_full_name;
  final String usual_first_name;
  final String url;
  final String phone;
  final String displayname;
  final String kind;
  final String image;
  final String link;
  final String versions;
  final String large;
  final String medium;
  final String small;
  final String micro;
  final bool staff;
  final int correction_point;
  final String pool_month;
  final String pool_year;
  final String location;
  final int wallet;
  final String anonymize_date;
  final String data_erasure_date;
  final String created_at;
  final String updated_at;
  final String alumnized_at;
  final bool alumni;
  final bool active;


  Student({
    this.id = "",
    this.email = "",
    this.login = "",
    this.first_name = "",
    this.last_name = "",
    this.usual_full_name = "",
    this.usual_first_name = "",
    this.url = "",
    this.phone = "",
    this.displayname = "",
    this.kind = "",
    this.image = "",
    this.link = "",
    this.versions = "",
    this.large = "",
    this.medium = "",
    this.small = "",
    this.micro = "",
    this.staff = false,
    this.correction_point = 0,
    this.pool_month = "",
    this.pool_year = "",
    this.location = "",
    this.wallet = 0,
    this.anonymize_date = "",
    this.data_erasure_date = "",
    this.created_at = "",
    this.updated_at = "",
    this.alumnized_at = '',
    this.alumni = false,
    this.active = true,
  });
}

